### ISSUE TITLE
naming convention for generated immutable class

### ISSUE THREAD

**Issue by qinfchen** [palantir/conjure-java-runtime#19]
Should the generated class be prefixed with `Immutable_` vs `Immutable`? Take TrustStoreConfiguration for example, the generated class is never exposed (using the builder) and prefixing `Immutable_` would help avoiding name collision with the classes with Immutable` prefix. 

I am curious on the naming convention, so we can add it to baseline and apply to other projects

**Comment by markelliot** [comment]
I think because the classes land in the same package it's not a concern, as I subscribe to the idea that a package namespace is owned by exactly one project in exactly one jar (this also keeps us ready for JDK9/Jigsaw). All things the same, I'd prefer to use the default from the Immutables library if non-detrimental, and per previous thing, I think non-detrimental.

Thoughts?

**Comment by qinfchen** [comment]
Can you elaborate on the JDK9 comment? I don't have a strong preference and so far I haven't seen any issues using the default setting from the library. Since we have inconsistent naming conventions across a few project, I would like to pick one and stick to it.

**Comment by markelliot** [comment]
For jigsaw, it's not legal to have the same package defined by two separate modules (basically a single jar): http://openjdk.java.net/projects/jigsaw/spec/sotms/. Security is applied at the module level, so I'm not really worried about conflicts, since they're resolvable entirely within the package space that this project takes.

**Comment by qinfchen** [comment]
sounds good.
