### ISSUE TITLE
@FormParam doesn't work

### ISSUE THREAD

**Issue by brahms** [palantir/conjure-java-runtime#240]
I attempted to use an earlier version of http-remoting (0.14) with the @FormParam annotation on my JaxRs client. The server never received the parameter, so could we verify/add support for @FormParam in http-remoting 1.0?

Thanks!

**Comment by uschi2000** [comment]
@j-baker you had some experiments with form params; what was the conclusion there?

**Comment by j-baker** [comment]
Form params with http-remoting are basically a no-go because the encoder doesn't get the media type or the annotations to act on and so it's difficult to determine (given a map or whatever) how you're meant to encode it.

We should consider picking up @chrisalice's annotation based contract (minor variation in fact) which would enable this kind of addition in a pluggable fashion (grep for it in the product she worked on for ages internally).

Would let you annotate individual methods with

@FeignEncoder(FormParamEncoder.class)

James

Sent from my iPhone

On Sep 29, 2016, at 19:32, Robert Fink <notifications@github.com<mailto:notifications@github.com>> wrote:

@j-bakerhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_j-2Dbaker&d=DQMGaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=mWGXbC_WERE__hOXR_n2ki4IPTM4A6g_eAzElU1LLuk&s=ElrMzLo4QkLO_MY035T_xkG8ohl9Io31KHSz4pYOS88&e= you had some experiments with form params; what was the conclusion there?

**Comment by j-baker** [comment]
Oh wait, it gets the request template (if you have the header at that point?) so you might be able to do it (just about) with another encoder - but yeah - not something remoting does well atm.

Sent from my iPhone

On Sep 29, 2016, at 19:51, James Baker <jbaker@palantir.com<mailto:jbaker@palantir.com>> wrote:

Form params with http-remoting are basically a no-go because the encoder doesn't get the media type or the annotations to act on and so it's difficult to determine (given a map or whatever) how you're meant to encode it.

We should consider picking up @chrisalice's annotation based contract (minor variation in fact) which would enable this kind of addition in a pluggable fashion (grep for it in the product she worked on for ages internally).

Would let you annotate individual methods with

@FeignEncoder(FormParamEncoder.class)

James

Sent from my iPhone

On Sep 29, 2016, at 19:32, Robert Fink <notifications@github.com<mailto:notifications@github.com>> wrote:

@j-bakerhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_j-2Dbaker&d=DQMGaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=mWGXbC_WERE__hOXR_n2ki4IPTM4A6g_eAzElU1LLuk&s=ElrMzLo4QkLO_MY035T_xkG8ohl9Io31KHSz4pYOS88&e= you had some experiments with form params; what was the conclusion there?

**Comment by brahms** [comment]
As a stopgap, I have FormParamEncoder object wrapped by this encoder to only use it when the target accepts a MediaType.APPLICATION_FORM_URLENCODED:

``` java
public class SometimesFormParamEncoder implements Encoder {
    private final Encoder delegate;
    private final FormParamEncoder formParamEncoder = new FormParamEncoder();

    public SometimesFormParamEncoder(Encoder delegate) {
        this.delegate = delegate;
    }

    @Override
    public void encode(Object object, Type bodyType, RequestTemplate template) throws EncodeException {
        Collection<String> contentTypes = template.headers().get(HttpHeaders.CONTENT_TYPE);
        String contentType = contentTypes != null ? Iterables.getFirst(contentTypes, null) : null;
        if (MediaType.APPLICATION_FORM_URLENCODED.equals(contentType)) {
            formParamEncoder.encode(object, bodyType, template);
        } else {
            delegate.encode(object, bodyType, template);
        }
    }
}
```

**Comment by markelliot** [comment]
It may make more sense to use the Retrofit http-remoting adapter, since Retrofit supports form params and we're expecting Retrofit contracts to use the default annotations rather than JaxRs annotations.

**Comment by markelliot** [comment]
We've made Retrofit and JaxRs implementations equivalent in terms of capability, so as a formal recommendation here: if you need form params, use Retrofit.
