### ISSUE TITLE
Propagate user-visible exception messages, even when includeStackTraceInErrors=false

### ISSUE THREAD

**Issue by pnepywoda** [palantir/conjure-java-runtime#243]
https://github.com/palantir/http-remoting/blob/develop/dropwizard-servers/src/main/java/com/palantir/remoting1/servers/JsonExceptionMapper.java#L62 only displays the errorId when includeStackTraceInErrors=false. It'd be useful to have something like UserVisibleException (what Metropolis named it long ago) which we'd check against and then always display the message

**Comment by nziebart** [comment]
Reviving this thread due to recent discussions with @sandorw @markelliot @ellisjoe 

One approach here would be to make the logic of logging and constructing a `SerializableError` pluggable, by proving a base exception class that looks something like this:

```
abstract class RemotingException extends RuntimeException {
    void log(Logger log, String errorId);
    SerializableError getError(String errorId);
}
```

This has a couple benefits:
1) it allows discriminating between safe/unsafe params when logging, as opposed to just shoving a formatted string into the exception constructor and logging that
2) the client can decide what level is appropriate for logging the exception (as opposed to `JsonExceptionMapper` logging everything at `ERROR`)
3) the client can decide if the message/stacktrace is ok to propagate

Downsides:
1) you can't easily flip a switch to turn on/off error propagation (though you could probably get around this by having a `getErrorWithStacktrace` method which is used if the flag is on)

**Comment by markelliot** [comment]
I think for future breaking releases I'd like to remove the option of propagating a stack trace, anyway.

I'm mostly in sync with your proposal but I'd skip the `log` endpoint in favor of something that had a constructor of the form

    RemotingException(String errorId, String englishMessage, Object... params)

Where we treat `params` as arguments for the message. I'd be open to the idea that we want key/value pairs, or willing to do the thing we're doing with `SafeParam` and have `UnsafeParam`, with both extending a root `Param` object so that you're explicitly required to provide a key and that we only accept one or the other in exceptions.

**Comment by nziebart** [comment]
Yep, that is what I was envisioning for the constructor. 

Having a `log` method allows the client to control how the message is actually logged (e.g., the log level, and what the message looks like). Not too concerned about this either way - I assume in your proposal the exception handler is extracting the message / parameters and doing the logging.

Is your thought around `SafeParam` / `UnsafeParam` that we define those objects here and have our logging libraries handle them appropriately?

**Comment by markelliot** [comment]
I think that'd be an okay solution/probably could have a separate repo/artifact since these things are unlikely to change once created.

I'd prefer not to allow tuning of log levels.

**Comment by pnepywoda** [comment]
RemoteException done in https://github.com/palantir/http-remoting-api/pull/9

**Comment by uschi2000** [comment]
will release in 3.0

**Comment by pnepywoda** [comment]
still waiting on https://github.com/palantir/http-remoting/pull/469

**Comment by pnepywoda** [comment]
@uschi2000  Release blockers https://github.com/palantir/http-remoting/labels/For-3.0.0
