### ISSUE TITLE
Remoting 3.3.0-rc1 Not Failing Over Correctly

### ISSUE THREAD

**Issue by sjohnsonpal** [palantir/conjure-java-runtime#530]
When testing http-remoting-3.3.0-rc1 we noticed that when a node that is receiving requests goes down, the client does not fail over to the next node in the list and instead just throws an exception. 

Previously http-remoting would fail over to the next node in the list in order to utilize a service configured to be highly available.

**Comment by uschi2000** [comment]
Can you provide a failing test?

**Comment by gauravtiwari89** [comment]
The failovers seem to work fine. Think the confusion stems from change in behavior from 2.x where by default a request tries all hosts before failing. What was the reason for changing that ?

**Comment by uschi2000** [comment]
The only change that I'm aware of (.. and there may be others..) is that as of 3.3.0-rc1 the client now respects `config.maxNumRetries()` instead of retrying `urls.size()` times. I think it'd be reasonable to change the default from 0 to, uhm, 3ish. (I had hoped to not release a 3.3.0 version yet because the retry work is still very much in progress. Made the rc1 because @meditativeape needed some other unrelated patch.)

FYI @meditativeape I think you had picked up the rc1 already, right? watch out for the retry config.

**Comment by meditativeape** [comment]
Gotcha, thanks for the heads-up. I think it would be reasonable to bump the default as you suggested, and change
https://github.com/palantir/http-remoting/blob/aafb00d031019c893c08b12b61c6511adbb44097/http-clients/src/main/java/com/palantir/remoting3/clients/ClientConfigurations.java#L63
to
`.maxNumRetries(max(DEFAULT_MAX_NUM_RETRIES, config.uris().size))`?

**Comment by uschi2000** [comment]
Fixed by https://github.com/palantir/http-remoting/pull/531
