### ISSUE TITLE
add host name as a tag on client metrics

### ISSUE THREAD

**Issue by ellisjoe** [palantir/conjure-java-runtime#581]
currently response metrics are recorded globally. the host name should be included as a tag on the metric so we can determine which specific hosts are unhealthy

**Comment by iamdanfox** [comment]
Clients are now constructed with a `HostEventsSink` (which we provide a `HostMetricsRegistry`) so that callers can determine how hosts are behaving:

https://github.com/palantir/conjure-java-runtime/blob/4.5.1/conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/JaxRsClient.java#L40

I think this means the outcome is now achieved, even if we don't record an explicit 'tag'.
