### ISSUE TITLE
Shared dispatcher is problematic for highly parallel clients

### ISSUE THREAD

**Issue by pkoenig10** [palantir/conjure-java-runtime#860]
In #706 a change was made to use a single global dispatcher for all clients. However we did not increase the maximum number of simultaneous requests.

Because of this, it is very easy to inadvertently saturate the dispatcher and cause slowness in requests to _all_ services. The ability to further parallelize workloads is then limited because you must take great care not to saturate the dispatcher with requests to a single client. This is particularly troublesome when calling APIs that only expose a singular endpoint and expect clients to do the parallelization.

In general, it seems incorrect to queue requests globally. This makes it possible for high-volume low-importance (willing to tolerate being queued) requests to starve low-volume high-importance requests.

**Comment by dansanduleac** [comment]
That change was made to relieve the burden on a high throughput internal application. The reason for it was to prevent the number of concurrent requests from increasing unboundedly, which is what happens when you create a client per request. That can then cause throughput to drop below that would be considered acceptable for that app.

Indeed as you point out, if you have a lot of different kind of requests then they can starve each other.

I see a couple of potential solutions here:
- allowing you to create clients with independent dispatchers like before, but in a more controlled fashion - e.g. creating clients out of a RateLimitedClientFactory, and allowing users to create multiple such factories each with their own dispatcher
- allowing clients to take a priority, and turning the global queue into a priority queue

I think the global queue is still a useful concept, as it's likely an app's performance will degrade if we allow the number of outgoing connections to increase unboundedly.
That's why both of these options allow implementers to have some confidence in the max number of concurrent requests.

**Comment by iamdanfox** [comment]
Closing out because we have now dialled up the max number of connections in the dispatcher to INT_MAX and rely on the concurrencylimiter to avoid overloading upstreams.

https://github.com/palantir/conjure-java-runtime/pull/1167
