### ISSUE TITLE
Retrofit 2.5 fails to validate paths with strings including some url encoded data

### ISSUE THREAD

**Issue by carterkozak** [palantir/conjure-java-runtime#930]
```
java.lang.IllegalArgumentException: @Path parameters shouldn't perform path traversal ('.' or '..'): foo+bar

	at retrofit2.RequestBuilder.addPathParam(RequestBuilder.java:113)
	at retrofit2.ParameterHandler$Path.apply(ParameterHandler.java:99)
	at retrofit2.RequestFactory.create(RequestFactory.java:108)
	at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:190)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:173)
```

These are valid parameters, they just need to be encode prior to being sent to a server.

**Comment by Shedon** [comment]
I'd like the issue to be fixed

**Comment by semenoh** [comment]
me to

**Comment by ash211** [comment]
Because of this issue this repo is still on retrofit 2.4.0 -- https://github.com/palantir/conjure-java-runtime/blob/cf9e9c7f484c0e1d5e5205134a2d29bee7ca69cb/versions.props#L51-L52

But now 2.4.0 has a known CVE: https://nvd.nist.gov/vuln/detail/CVE-2018-1000844 which is being flagged in internal vulnerability scanners, so we need to get off 2.4.0 shortly.

**Comment by bmarcaur** [comment]
No longer an issue with #1853, CJR no longer uses retrofit.
